### ISSUE TITLE
Can't get it to work with esx_inventory hud?

### ISSUE THREAD

**Issue by RagingNaClholic** [MacieGx/esx_planting#5]
I have everything set up and in my database and I have the seeds in my inventory, (esx_inventoryhud) but when I go to the location and try to use it inventory hud doesnt give me the option to use, any help for this amazing script would be appreciated.

**Comment by MacieGx** [comment]
Solved via discord.
The problem was that the @RagingNaClholic forgot to add script to server.cfg

**Comment by Ventrix1994** [comment]
I am having this same issue, but I have the resource started. Also using Inventory Hud
