### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Matetv** [MacieGx/esx_planting#6]
Unfortunately the script does not work! Sit now for 3 days on the script! :frowning: What am I doing wrong? I do not get info that I can grow! “Seed_weed” in database, but I can not get any interaction in. Can someone help me?

**Comment by MacieGx** [comment]
You should add **seed_weed** item into your db.
Item name is case sensitive.

**Comment by Matetv** [comment]
"seed_weed" two seeds were now used, more leider not. Aber es kommen keine Pflanzen!

**Comment by Owby** [comment]
You have to stay on a place where you can farm weed. then go into your inventory and use the seed.
