### ISSUE TITLE
No issue, just wanted to share my script.

### ISSUE THREAD

**Issue by crixzgamez** [MacieGx/esx_planting#8]
Feel free to use my script as wanted,
Thanks to MacieG for the awesome support trough Discord when this script was inactively used a few months back!

please read the readme before changing anything,
the config is somehow described on how to change things.
This script comes with planting, processing, and works well!
download link:
https://www.mediafire.com/file/av0y0883r6tyw7s/esx_planting.rar/file

**Comment by sadoj-kuro** [comment]
no sql file ?

**Comment by MacieGx** [comment]
Would be great if you would fork this repository and push changes there. Not everyone wants to download unverified packed files @crixzgamez 😈

**Comment by crixzgamez** [comment]
Cant delete the post.
